Category.all.each do |category|
  category.destroy
end

Question.all.each do |question|
  question.destroy
end


c1=Category.create(name: "Growing Up")
c2=Category.create(name: "Family Heritage")
c3=Category.create(name: "Love & Relationships")  
c4=Category.create(name: "Parenthood") 
c5=Category.create(name: "Personal Anecdotes") 
c6=Category.create(name: "Health History")

Question.create(inquiry: "When and where were you born?", category_id: c1.id)
Question.create(inquiry:"Where did you grow up?", category_id: c1.id)
Question.create(inquiry: "What was it like?", category_id: c1.id)
Question.create(inquiry: "Who were your parents?", category_id: c1.id)
Question.create(inquiry: "What were your parents like?", category_id: c1.id)
Question.create(inquiry: "How was your relationship with your parents?", category_id: c1.id)
Question.create(inquiry: "Did you get into trouble? What was the worst thing you did?", category_id: c1.id)
Question.create(inquiry: "Do you have any siblings? What were they like growing up?", category_id: c1.id)
Question.create(inquiry: "What did you look like as a child? As a teenager?", category_id: c1.id)
Question.create(inquiry: "How would you describe yourself as a child? Were you happy?", category_id: c1.id)
Question.create(inquiry: "What is your best memory of childhood? Worst?", category_id: c1.id)
Question.create(inquiry: "Did you have a nickname? How did you get it?", category_id: c1.id)
Question.create(inquiry: "Who were your best friends? What were they like?", category_id: c1.id)
Question.create(inquiry: "How would you describe a perfect day when you were young?", category_id: c1.id)
Question.create(inquiry: "What did you think your life would be like when you were older?", category_id: c1.id)
Question.create(inquiry: "Do you have any favorite stories from your childhood?", category_id: c1.id)

Question.create(inquiry: "What is your ethnic background?", category_id: c2.id)
Question.create(inquiry: "Where is your moms family from? Where is your dads family from?", category_id: c2.id)
Question.create(inquiry: "Have you ever been back to your familys place of origin? What was that experience like?", category_id: c2.id)
Question.create(inquiry: "What traditions have been passed down in your family?", category_id: c2.id)
Question.create(inquiry: "Who were your favorite relatives?", category_id: c2.id)
Question.create(inquiry: "Do you remember any of the stories your relatives used to tell you?", category_id: c2.id)
Question.create(inquiry: "What are the classic family stories? Jokes? Songs?", category_id: c2.id)

Question.create(inquiry: "When did you first fall in love?", category_id: c3.id)
Question.create(inquiry: "When was your first serious relationship?", category_id: c3.id)
Question.create(inquiry: "Do you believe in love at first sight?", category_id: c3.id)
Question.create(inquiry: "What lessons have you learned from your relationships?", category_id: c3.id)
Question.create(inquiry: "How did you meet your husband/wife?", category_id: c3.id)
Question.create(inquiry: "How did you know your husband/wife was the one?", category_id: c3.id)
Question.create(inquiry: "How did you propose?", category_id: c3.id)
Question.create(inquiry: "Did you ever get divorced? Can you tell me about it?", category_id: c3.id)
Question.create(inquiry: "What advice do you have for young couples?", category_id: c3.id)
Question.create(inquiry: "Do you have any favorite stories from your marriage or about your husband/wife?", category_id: c3.id)

Question.create(inquiry: "When did you first find out that you would be a parent? How did you feel?", category_id: c4.id)
Question.create(inquiry: "What was going through your head when you first saw your children?", category_id: c4.id)
Question.create(inquiry: "How did you choose your childrens names?", category_id: c4.id)
Question.create(inquiry: "What were your children like as babies? As young children?", category_id: c4.id)
Question.create(inquiry: "Do you remember any of the songs you used to sing to your children? Can you sing them now?", category_id: c4.id)
Question.create(inquiry: "What were the sibling rivalries like?", category_id: c4.id)
Question.create(inquiry: "What were the hardest moments you had when your children were growing up?", category_id: c4.id)
Question.create(inquiry: "If you could do everything again, would you raise your children differently?", category_id: c4.id)
Question.create(inquiry: "What advice would you give your children about raising their own kids?", category_id: c4.id)
Question.create(inquiry: "What are your dreams for your children?", category_id: c4.id)
Question.create(inquiry: "Are you proud of your children?", category_id: c4.id)
Question.create(inquiry: "How has being a parent changed you?", category_id: c4.id)
Question.create(inquiry: "What are your favorite stories about your kids?", category_id: c4.id)

Question.create(inquiry: "What was the happiest moment of your life? The saddest?", category_id: c5.id)
Question.create(inquiry: "Who was the most important person in your life? Can you tell me about him or her?", category_id: c5.id)
Question.create(inquiry: "Who has been the biggest influence on your life? What lessons did that person teach you?", category_id: c5.id)
Question.create(inquiry: "Who has been the kindest to you in your life?", category_id: c5.id)
Question.create(inquiry: "It has been said that after they pass away, the most important people in our lives live within us. Is there anyone from your past that lives within you?", category_id: 4)
Question.create(inquiry: "What are the most important lessons you have learned in life?", category_id: c5.id)
Question.create(inquiry: "What is your earliest memory?", category_id: c5.id)
Question.create(inquiry: "Are there any words of wisdom you would like to pass along to future generations?", category_id: c5.id)
Question.create(inquiry: "What are you proudest of in your life?", category_id: c5.id)
Question.create(inquiry: "When in life have you felt most alone?", category_id: c5.id)
Question.create(inquiry: "How has your life been different than what you imagined?", category_id: c5.id)
Question.create(inquiry: "How would you like to be remembered?", category_id: c5.id)
Question.create(inquiry: "Do you have any regrets?", category_id: c5.id)
Question.create(inquiry: "What does your future hold?", category_id: c5.id)
Question.create(inquiry: "Is there anything that you have never told anyone but want to tell them now?", category_id: c5.id)
Question.create(inquiry: "What have you learned from life? The most important things?", category_id: c5.id)
Question.create(inquiry: "Do you believe in an after-life?", category_id: c5.id)

Question.create(inquiry: "What illnesses or genetic diseases run in your family?", category_id: c6.id)
Question.create(inquiry: "Are you an organ donor?", category_id: c6.id)
Question.create(inquiry: "Have you ever been seriously ill or hospitalized?", category_id: c6.id)
Question.create(inquiry: "Have you ever had any surgical procedures? If so, what?", category_id: c6.id)
Question.create(inquiry: "Are you allergic or have you experienced an unusual reaction to any drugs? If yes, which ones?", category_id: c6.id)
Question.create(inquiry: "Do you use tobacco or drink alcohol? If so, how often?", category_id: c6.id)
Question.create(inquiry: "Have you ever had problems with general or regional anesthesia?", category_id: c6.id)
Question.create(inquiry: "Have you ever had a serious illness such as cancer, diabetes, heart or lung disease (incuding heart surgery and/or stroke), convulsions, chest pains, asthma or shortness of breath?", category_id: c6.id)
Question.create(inquiry: "Have you ever been refused as a blood donor or had problems donating blood?", category_id: c6.id)



